import Groq from 'groq-sdk';

export async function generateArticle(apiKey: string, prompt: string, model: string = 'llama3-8b-8192'): Promise<{ success: boolean, content: string }> {
    const groq = new Groq({ apiKey });

    try {
        const chatCompletion = await groq.chat.completions.create({
            messages: [{ role: 'user', content: prompt }],
            model: model,
        });

        const content = chatCompletion.choices[0]?.message?.content;
        if (content) {
            return { success: true, content: content };
        } else {
            return { success: false, content: 'No content generated by Groq.' };
        }
    } catch (error) {
        console.error('Error generating article with Groq:', error);
        return { success: false, content: `Failed to generate article. Groq API Error: ${error.message}` };
    }
}

export async function listModels(apiKey: string): Promise<any[]> {
    try {
        const response = await fetch('https://api.groq.com/openai/v1/models', {
            headers: {
                'Authorization': `Bearer ${apiKey}`,
            },
        });

        if (!response.ok) {
            console.error('Failed to fetch models from Groq API:', response.statusText);
            return [];
        }

        const data = await response.json();
        return data.data || [];
    } catch (error) {
        console.error('Error listing Groq models:', error);
        return [];
    }
}
