import fs from 'node:fs';
import path from 'node:path';
import { loadEnv, CFG } from './config.mjs';
import { kvGetJson, kvPut } from './kv.mjs';
import { generateScript, generateImagePrompts, generateTitle } from './groq.mjs';
import { downloadImages } from './images.mjs';
import { ttsSegments, splitScript } from './tts.mjs';
import { renderSlideshow } from './render.mjs';
import { uploadVideo } from './upload.mjs';
import { loadTokens } from './oauth.mjs';
import { notifyChat } from './telegram.mjs';

const sleep = ms => new Promise(r => setTimeout(r, ms));
const esc = s => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

async function getJobs() {
    const jobs = await kvGetJson('yt_jobs', []);
    return Array.isArray(jobs) ? jobs : [];
}

async function updateJob(id, patch) {
    const jobs = await getJobs();
    const idx = jobs.findIndex(j => j.id === id);
    if (idx === -1) return;
    jobs[idx] = { ...jobs[idx], ...patch, updatedAt: Date.now() };
    await kvPut('yt_jobs', JSON.stringify(jobs));
}

async function processJob(job) {
    const chatId = job.chat_id;
    const workDir = path.join(CFG.OUT_DIR, job.id);
    fs.mkdirSync(workDir, { recursive: true });

    await notifyChat(chatId, `🎬 <b>Rendering video:</b> <code>${esc(job.topic)}</code>…`);

    const formats = job.format === 'long' ? ['long'] : job.format === 'short' ? ['short'] : ['long', 'short'];
    const results = [];

    for (const format of formats) {
        const kind = format;
        const script = await generateScript(job.topic, kind);
        const prompts = await generateImagePrompts(script, kind);
        const orientation = kind === 'short' ? 'vertical' : 'landscape';
        const images = await downloadImages(prompts, workDir, orientation);
        const segments = splitScript(script, images.length);
        const narrations = await ttsSegments(segments, workDir);

        const outFile = path.join(workDir, `${kind}_${job.id}.mp4`);
        await renderSlideshow({ images, narrations, out: outFile, orientation, music: CFG.MUSIC });

        const title = await generateTitle(job.topic, script);

        const settings = (await kvGetJson(`yt_settings_${chatId}`, {})) || {};
        const titlePrefix = settings.titlePrefix || '';
        const tags = (settings.tags || '').split(',').map(t => t.trim()).filter(Boolean);
        if (kind === 'short') tags.push('shorts');
        const privacy = settings.privacy || CFG.PRIVACY || 'private';

        const fullTitle = kind === 'short'
            ? `${titlePrefix ? titlePrefix + ' ' : ''}${title.slice(0, 90)} #Shorts`
            : `${titlePrefix ? titlePrefix + ' ' : ''}${title}`;

        const videoId = await uploadVideo({
            filePath: outFile,
            title: fullTitle,
            description: `${job.topic}\n\nAuto-generated by CreatorBot.\n\n${tags.map(t => `#${t.replace(/[^a-zA-Z0-9_]/g, '')}`).join(' ')}`,
            tags,
            privacyStatus: privacy,
        });

        results.push({ kind, videoId });
        console.log(`Uploaded ${kind} video: https://youtu.be/${videoId}`);
    }

    await updateJob(job.id, {
        status: 'done',
        url: results.length ? `https://youtu.be/${results[0].videoId}` : undefined,
        videoId: results[0]?.videoId,
        error: undefined,
    });

    const links = results.map(r => `${r.kind === 'short' ? 'Shorts' : 'Video'}: <a href="https://youtu.be/${r.videoId}">watch</a>`).join(' · ');
    await notifyChat(chatId, `✅ <b>Uploaded to YouTube:</b> <code>${esc(job.topic)}</code>\n${links}`);
}

async function pollOnce() {
    const jobs = await getJobs();
    const pending = jobs.find(j => j.status === 'pending');
    if (!pending) return false;

    await updateJob(pending.id, { status: 'processing' });
    try {
        await processJob(pending);
    } catch (e) {
        console.error(`Job ${pending.id} failed:`, e);
        await updateJob(pending.id, { status: 'failed', error: e.message });
        await notifyChat(pending.chat_id, `❌ <b>Video failed:</b> <code>${esc(pending.topic)}</code>\n<code>${esc(e.message)}</code>`);
    }
    return true;
}

async function main() {
    loadEnv();
    if (!loadTokens()) {
        console.error('Not connected to YouTube. Run: node oauth.mjs');
        process.exit(1);
    }
    const once = process.argv.includes('--once');
    console.log(`CreatorBot YouTube pipeline started (poll every ${CFG.POLL_SECONDS}s)${once ? ' — once' : ''}`);
    do {
        try {
            await pollOnce();
        } catch (e) {
            console.error('Poll error:', e.message);
        }
        if (once) break;
        await sleep(CFG.POLL_SECONDS * 1000);
    } while (true);
}

if (process.argv[1] && process.argv[1].endsWith('pipeline.mjs')) {
    main().catch(e => {
        console.error('Pipeline fatal:', e.message);
        process.exit(1);
    });
}